build: Add Meson build system
electrickite/batsignal pull request #16
Opened 2022-01-31 19:11 UTC by concatime

Hi.
This PR adds support for Meson and [Muon](https://sr.ht/~lattis/muon/) (C99 implementation of Meson subset).
Meson & cie is more reliable and easier to validate.
So you only need a C99 compiler to build this project (muon+samurai).
WDYT?

2022-01-31 21:16 UTC, electrickite commented
Thanks for the suggestion. While I'm not necessarily opposed to different build systems, I would prefer to keep the project as simple and "boring" as possible. For a program this small, what problems does Meson help to solve?

2022-01-31 21:46 UTC, concatime commented
Well, using a properly defined build system is well suited for small programs. (GNU) Makefile should be used in more complex system (like Linux kernel). No need to redefine implicit rules. The Makefile in this project is not POSIX, even with `.POSIX:` at line 1. batsignal can’t even be built with BSD make. `gmake CFLAGS=...` breaks the Makefile. `env CFLAGS=... make -e` too. It’s too fragile. With Meson, I can easily add warnings (`warning_level`), PIE (`b_pie`), LTO (`b_lto`), sanatizers, static binary, etc.
So yeah, the list goes on and on :)

2022-02-01 02:11 UTC, eli-schwartz requested changes

2022-02-01 02:11 UTC, eli-schwartz commented on .gitignore
> +build
This is not necessary. The user might configure with a build directory called `builddir/` and your gitignore would not take effect :) but on the other hand, Meson itself will create `builddir/.gitignore` which ignores `*`.

2022-02-01 02:11 UTC, eli-schwartz commented on meson.build
> +  configuration : config)
Since meson 0.49 (and compatible with muon too) you can do:
```suggestion
configure_file(output : 'config.h', configuration : {'VERSION': meson.project_version()})
```

2022-02-01 02:11 UTC, eli-schwartz commented on meson.build
> +  libm = cc.find_library('m')
https://mesonbuild.com/howtox.html#add-math-library-lm-portably

Just search for it but do not make it required. On all platforms where it is needed, it will be found. On many platforms, it won't be there, but will be part of libc directly.

2022-02-01 02:11 UTC, eli-schwartz commented on meson.build
> +    capture: true,
Feed and capture require invoking a python program to wrap stdin/stdout. Anyway, can't you just make this a configure_file too?

2022-02-01 03:28 UTC, electrickite commented
Thanks for the feedback. The latest commit makes the `Makefile` file a bit more portable. (And moves to C11, primarily for FreeBSD compat). Compiles on the five tested Linux distros and FreeBSD using `make` and `gmake`. Also improves `CFLAGS` handling. Given the simplicity of the make targets, I don't know that introducing a new build system, dependency on python, etc is worth it.

2022-02-01 03:35 UTC, eli-schwartz commented on meson.build
> +libm_ok = compat or cc.has_function('round',
This muon compat thing seems to be because has_function is buggy and returns that the function is unavailable when it should be there.

I submitted a simple patch to muon which fixes this: https://lists.sr.ht/~lattis/muon/patches/28910

2022-02-02 00:10 UTC, concatime commented on meson.build
> +  configuration : config)
Your recommended approach does not quote the version. It would generate `1.2.3` instead of `"1.2.3"`.

2022-02-02 00:25 UTC, eli-schwartz commented on meson.build
> +  configuration : config)
Right, sorry, that was silly of me.

2022-02-02 01:18 UTC, concatime commented on meson.build
> +    capture: true,
Oh well, thank you!

2022-02-02 01:19 UTC, concatime commented on meson.build
> +libm_ok = compat or cc.has_function('round',
Updated my local version of muon, and it works. Nice!

2022-02-02 01:22 UTC, concatime commented on meson.build
> +  libm = cc.find_library('m')
Fixed, thank you :)

2022-02-02 01:59 UTC, eli-schwartz commented on meson.build
> +  install_dir : get_option('mandir'))
mandir doesn't include the `man1/` subdirectory, it's just the base directory e.g. `/usr/share/man`

That being said, `install_man()` can install file objects, such as that returned by `configure_file()`.

2022-02-02 02:11 UTC, concatime commented on meson.build
> +  install_dir : get_option('mandir'))
`install_man()` does not work on muon :(

2022-07-28 15:52 UTC, electrickite commented
Thanks again for the suggestion, but going to close out this PR for the reasons discussed in the PR comments.

2022-07-28 15:52 UTC, closed without merging